name: Gold Brick Studios
favicon: null
layout_spectrum: 0.7406593665946275
typography_spectrum: 0.07533150049857795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.17619042959995568
  lightness: 0.5096742829773575
  saturation: 0.4719997067004442
  rhythmicContrast: 0.02730788430199027
purpose: []
